pokedex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pokemons.urls')),
]

pokemons/urls.py
from django.urls import path

from . import views

app_name = 'pokemons'

urlpatterns = [
    path('', views.home, name="home"),
    path('search/', views.search_results, name="search_results"),
    path('type/<str:name>/', views.pkm_type, name="tipo"),
    path('ability/<str:name>/', views.ability, name="ability"),
    path('generation/<str:name>/', views.generation, name="generation"),
    path('pokemon/<int:number>/', views.pokemon, name="pokemon"),
]

pokemons/models.py
from django.db import models

# Create your models here.


class PkmType(models.Model):
    name = models.CharField(max_length=35)

    def __str__(self):
        return self.name


class PkmAbility(models.Model):
    name = models.CharField(max_length=35)

    def __str__(self):
        return self.name


class Evolutions(models.Model):
    number = models.IntegerField()
    first_form = models.CharField(max_length=65)

    def __str__(self):

        return self.first_form


class Generation(models.Model):
    name = models.CharField(max_length=35)

    def __str__(self):

        return self.name


class Pokemon(models.Model):

    number = models.IntegerField()
    name = models.CharField(max_length=65)
    picture = models.URLField()
    evolution_chain_number = models.ForeignKey(
        Evolutions,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        default=None,)
    #  physical attributes
    height = models.IntegerField()
    weight = models.IntegerField()
    #  status base
    hp = models.IntegerField()
    attack = models.IntegerField()
    defense = models.IntegerField()
    special_attack = models.IntegerField()
    special_defense = models.IntegerField()
    speed = models.IntegerField()
    #  pokemon types
    pkm_types = models.ManyToManyField(PkmType)
    color_type = models.CharField(max_length=35)
    abilities = models.ManyToManyField(PkmAbility)

    generation = models.ForeignKey(
        Generation,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        default=None,)

    def __str__(self):

        infos = str(self.number) + ' - ' + self.name

        return infos

pokemons/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404, get_object_or_404, render

from .models import Pokemon

# Create your views here.


def home(request):

    lis_all = Pokemon.objects.all()
    paginator = Paginator(lis_all, 20)
    pagina = request.GET.get('pagina')
    pkmList = paginator.get_page(pagina)

    return render(request, 'pokemons/pages/home.html', context={

        'pokemonItens': pkmList,
    })


def search_results(request):
    if request.method == 'GET':
        query = request.GET.get('query')
        results = Pokemon.objects.filter(name__icontains=query)
    return render(request, 'pokemons/pages/search-results.html', context={
        'results': results,
    })


def pkm_type(request, name):

    pkmList = get_list_or_404(
        Pokemon.objects.filter(
            pkm_types__name=name
        ).order_by('number'))

    title = ''
    for pokemon in pkmList:
        for pkm_type in pokemon.pkm_types.all():
            if pkm_type.name.lower() == name.lower():
                title = pkm_type.name
                break
        if title:
            break

    if not title and pkmList:
        title = "NotFound"

    return render(request, 'pokemons/pages/tipos.html', context={

        'pokemonItens': pkmList,
        'title': title,
    })


def ability(request, name):

    pkmList = get_list_or_404(
        Pokemon.objects.filter(
            abilities__name=name
        ).order_by('number'))

    title = ''
    for pokemon in pkmList:
        for pkm_ab in pokemon.abilities.all():
            if pkm_ab.name.lower() == name.lower():
                title = pkm_ab.name
                break
        if title:
            break

    if not title and pkmList:
        title = "NotFound"

    return render(request, 'pokemons/pages/ability.html', context={

        'pokemonItens': pkmList,
        'title': title,
    })


def generation(request, name):

    pkmList = get_list_or_404(
        Pokemon.objects.filter(
            generation__name=name
        ).order_by('number'))

    title = ''
    for pokemon in pkmList:
        if pokemon.generation.name == name.lower():
            title = pokemon.generation.name
            break
        if title:
            break

    if not title and pkmList:
        title = "NotFound"

    return render(request, 'pokemons/pages/generation.html', context={

        'pokemonItens': pkmList,
        'title': title,
    })


def pokemon(request, number):
    pkm = get_object_or_404(Pokemon, number=number)
    pkmevo = get_list_or_404(
        Pokemon,
        evolution_chain_number=pkm.evolution_chain_number)

    return render(request, 'pokemons/pages/pokemon-view.html', context={

        'pkm': pkm,
        'title': pkm.name,
        'evos': pkmevo,
    })

pokemons/templates/pokemons/pages/ability.html
{% extends 'global/base.html' %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}

    <span class="text-search">all pokemons that have the ability: {{title}}</span>

    <ol id="pokemonList" class="pokemons">

        <!-- pokemons here -->

        {% for item in pokemonItens %}
            {% include 'pokemons/partials/pokemon-item.html' %}
        {% endfor %}
        
    </ol>

{% endblock content %}

pokemons/templates/pokemons/pages/generation.html
{% extends 'global/base.html' %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}

    <span class="text-search">all pokemon that are from this generation: {{title}}</span>

    <ol id="pokemonList" class="pokemons">

        <!-- pokemons here -->

        {% for item in pokemonItens %}
            {% include 'pokemons/partials/pokemon-item.html' %}
        {% endfor %}
        
    </ol>

{% endblock content %}

pokemons/templates/pokemons/pages/home.html
{% extends 'global/base.html' %}
{% block title %}DJANGO-DEX{% endblock title %}

{% block content %}

    <ol id="pokemonList" class="pokemons">

        <!-- pokemons here -->

        {% for item in pokemonItens %}
            {% include 'pokemons/partials/pokemon-item.html' %}
        {% endfor %}
        
    </ol>

{% endblock content %}

{% block buttons %}

    <div class="but-page">

        {% if pokemonItens.has_previous %}
            <a href="?pagina={{ pokemonItens.previous_page_number }}">Previus Page</a>
        {% endif %}

        {% if pokemonItens.has_next %}
            <a href="?pagina={{ pokemonItens.next_page_number }}">Next Page</a>
        {% endif %}


    </div>


{% endblock buttons %}

pokemons/templates/pokemons/pages/pokemon-view.html
{% extends 'global/base.html' %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}

    {% include 'pokemons/partials/pkm-picture.html' %}
    {% include 'pokemons/partials/pkm-status.html' %}
    {% include 'pokemons/partials/pkm-evolve.html' %}

{% endblock content %}

{% block buttons %}

    <div class="but-page">

        {% if pkm.number >= 2 %}
            <a href="{% url 'pokemons:pokemon' pkm.number|add:"-1" %}">Previus Pokemon</a>
        {% endif %}

        {% if pkm.number <= 808 %}
            <a href="{% url 'pokemons:pokemon' pkm.number|add:"1" %}">Next Pokemon</a>
        {% endif %}

    </div>


{% endblock buttons %}

pokemons/templates/pokemons/pages/search-results.html
{% extends 'global/base.html' %}
{% block title %}DJANGO-DEX{% endblock title %}

{% block content %}

    <ol id="pokemonList" class="pokemons">

        {% for item in results %}

            {% include 'pokemons/partials/pokemon-item.html' %}
        
        {% empty %}

            <div class="center m-x">

                <h1>Pokemon not Found</h1>
                
            </div>

        {% endfor %}
        
    </ol>

{% endblock content %}

pokemons/templates/pokemons/pages/search_results.html
{% extends 'global/base.html' %}
{% block tittle %}DJANGO-DEX{% endblock tittle %}

{% block content %}

    <ol id="pokemonList" class="pokemons">

        {% for result in results %}
            {% include 'pokemons/partials/pokemon-item.html' %}
        
        {% empty %}

            <div class="center m-x">

                <h1>Pokemon not Found</h1>
                
            </div>

        {% endfor %}
        
    </ol>

{% endblock content %}

pokemons/templates/pokemons/pages/tipos.html
{% extends 'global/base.html' %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}

    <ol id="pokemonList" class="pokemons">

        <!-- pokemons here -->

        {% for item in pokemonItens %}
            {% include 'pokemons/partials/pokemon-item.html' %}
        {% endfor %}
        
    </ol>

{% endblock content %}

pokemons/templates/pokemons/partials/pkm-evolve.html
<div class="container evo-container">

    <div class="titulo">

        <p>Pokemon from this evolution chain:</p>

    </div>
    

    <div class="evolutions-detail">
        {% for evo in evos  %}
    
            <div class="evo-pkm">

                <div class="evo-picture">

                    <a href="{% url 'pokemons:pokemon' evo.number %}">
                        <img class="picture-pkm" src="{{evo.picture}}" alt="{{evo.name}}">
                    </a>

                </div>
                <div class="evo-name-number">

                    <p class="evo-name">{{evo.name}} Nº {{ evo.number|stringformat:"03d" }}</p>

                </div>


            </div>
    
        {% endfor %}

    </div>

</div>

pokemons/templates/pokemons/partials/pkm-picture.html
<div class="container {{pkm.color_type}} main-picture-container">

    <div class="left-container container container">

        <div class="number-cont">
            <div class="number-container container">

                <p class="number">#{{ pkm.number|stringformat:"03d" }}</p>
                <a href="{% url 'pokemons:generation' pkm.generation %}" class="gen">{{ pkm.generation }}</a>
        
            </div>

        </div>

    
        <div class="name-container container">
    
            <p class="name">{{ pkm.name }}</p>
    
        </div>
    </div> 


    <div class="container picture-container right-container">

        <img class="pkm-imagem" src="{{pkm.picture}}" alt="{{ pkm.name }}">
        <ol class="types">

            {% for tipo in pkm.pkm_types.all %}

                <li class="typein {{tipo}}">
                    <a href="{% url 'pokemons:tipo' tipo %}">{{tipo}}</a>
                </li>
            
            {% endfor %}

    </div>

</div>

pokemons/templates/pokemons/partials/pkm-status.html
<div class="container stats-container">

    <div class="table-stat">

        <table class="table-stat">
            <thead>
    
                <caption>Base Stats</caption>
    
                <tr>
                    <th>statistic</th>
                    <th>value</th>
                </tr>
    
            <tbody>
    
                <tr>
                    <td>hp</td>
                    <td>{{pkm.hp}}</td>
                </tr>
                <tr>
                    <td>attack</td>
                    <td>{{pkm.attack}}</td>        
                </tr>
                <tr>
                    <td>defense</td>
                    <td>{{pkm.defense}}</td>
                </tr>
                <tr>
                    <td>special attack</td>
                    <td>{{pkm.special_attack}}</td>
                </tr>
                <tr>
                    <td>special defense</td>
                    <td>{{pkm.special_defense}}</td>
                </tr>
                <tr>
                    <td>speed</td>
                    <td>{{pkm.speed}}</td>
                </tr>
            </tbody>
            </thead>
        </table>

    </div>

    <div class="table-stat">

        <table>
            <thead>
    
                <caption>physical attributes</caption>
    
                <tr>
                    <th>statistic</th>
                    <th>value</th>
                </tr>
    
            <tbody>
    
                <tr>
                    <td>height</td>
                    <td>{{pkm.height}}</td>
                </tr>
                <tr>
                    <td>weight</td>
                    <td>{{pkm.weight}}</td>        
                </tr>
            </tbody>
            </thead>
        </table>

    </div>
    
    <div class="table-stat">

        <table>
            <thead>
    
                <caption>Abilities</caption>
    
                <tr>
                    <th></th>
                </tr>
    
            <tbody>
    
            {% for ability in pkm.abilities.all %}
                <tr>
                    <td><a href="{% url 'pokemons:ability' ability.name %}">{{ability.name}}</a></td>
                </tr>    
            {% endfor %}
    
    
            </tbody>
            </thead>
        </table>

    </div>

</div>

pokemons/templates/pokemons/partials/pokemon-item.html
<li class="pokemon {{item.color_type}}">

    <div class="infos">

        <img src="{{item.picture}}" alt="{{item.name}}">

    </div>

    <div class="detail">

        <div class="identify">
            
            <a href="{% url 'pokemons:pokemon' item.number %}"  class="name" >{{item.name}}</a>
            <span class="number">#{{item.number|stringformat:"03d"}}</span>
            
        </div>

        <ol class="types">

            {% for tipo in item.pkm_types.all %}

                <li class="type {{tipo}}">
                    <a href="{% url 'pokemons:tipo' tipo %}">{{tipo}}</a>
                </li>
            
            {% endfor %}

        </ol>

    </div>
</li>

pokemons/templates/pokemons/partials/search-buttom.html
<div class="search-container">
    <form method="get" action="{% url 'pokemons:search_results' %}" class="search-form">

        <input type="search" name="query" class="search-input" placeholder="Search by pokemon name">
        <button type="submit" class="search-button"><i class="fas fa-search"></i></button>

    </form>
</div>